Bug/fix release pipeline (#22)
Fix the pipeline

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,4 +1,4 @@
-name: CI Pipeline
+name: Main Pipeline
 
 on:
   workflow_dispatch:
@@ -15,8 +15,10 @@ jobs:
 
     strategy:
       matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12"]
-        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
+        python-version: ["3.9"]
+        os: ["ubuntu-latest"]
+        # python-version: ["3.9", "3.10", "3.11", "3.12"]
+        # os: ["windows-latest", "ubuntu-latest", "macos-latest"]
 
     steps:
     - name: Checkout Repository
@@ -47,35 +49,75 @@ jobs:
   release:
     needs: build
     runs-on: ubuntu-latest
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+    if: github.event_name == 'push' && github.ref == 'refs/heads/bug/fix-release-pipeline'
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Set up PDM
-        uses: pdm-project/setup-pdm@v3
-        with:
-          python-version: "3.9"
-          cache: true
-          cache-dependency-path: '**/pdm.lock'
-
-      - name: Install dependencies
-        run: pdm sync
-
       - name: Bot Defaults
         uses: devlooped/actions-bot@v1.0.1
         with:
           github-token: ${{ secrets.SOUYANG_GITHUB_TOKEN }}
     
       - name: Bump Patch Version
-        run: .github/workflows/bump_version.sh
+        run: |
+          git pull --no-edit origin ${ github.event.ref }
+          CURRENT_VERSION=$(awk -F '"' '/^version/{print $2}' "pyproject.toml")
+          pdm bumpversion --current-version $CURRENT_VERSION patch pyproject.toml src/unit_grader/__init__.py --verbose --no-configured-files
+          NEW_VERSION=$(awk -F '"' '/^version/{print $2}' "pyproject.toml")
+          
+          # Check if there are changes before committing
+          if git diff --exit-code; then
+          echo "Version is not updated in pyproject.toml."
+          exit 1 # Exit with non-zero exit code to indicate failure
+          else
+          git remote set-url origin https://x-access-token:${{secrets.SOUYANG_GITHUB_TOKEN }}@github.com/souyang/unit-grader 
+          # Commit and push the change on pyproject.toml
+          git add pyproject.toml
+          git commit -m "[Bot] Updating version from ${CURRENT_VERSION} to ${NEW_VERSION}"
+          git push
+          # Create and publish a new release tag
+          TAG_NAME="v$NEW_VERSION"
+          if git rev-parse -q --verify "refs/tags/$TAG_NAME" > /dev/null; then
+              echo "Tag $TAG_NAME exists. Deleting remotely..."
+              git push origin :"$TAG_NAME"
+              echo "Tag $TAG_NAME deleted remotely."
+          else
+              echo "Tag $TAG_NAME does not exist."
+          fi              
+          git tag -a "$TAG_NAME" -m "Releasing version $NEW_VERSION"
+          git push origin "$TAG_NAME"
+          echo "Tag $TAG_NAME is created remotely."  
+          git tag -l --sort=-version:refname "v*"
+          fi
                      
       - name: Create Release
-        run: .github/workflows/create_release.sh
+        run: pdm publish --username ${ secrets.PYPI_USERNAME } --password ${ secrets.PYPI_PASSWORD }
   
   build_deploy_docs:
     needs: release
     runs-on: ubuntu-latest
     steps:
-      - name: Build and deploy Docs
-        uses: ./build-deploy-docs.yaml
+      - name: Build API Documentation
+        run: pdm run doc
+
+      - name: Deploy to Netlify
+        id: netlify
+        uses: nwtgck/actions-netlify@v1
+        with:
+          production-branch: "main"
+          publish-dir: "./docs/_build/html"
+          deploy-message: "Deploy from GitHub Actions"
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          enable-pull-request-comment: true
+          enable-commit-comment: false
+          production-deploy: true
+        env:
+          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
+          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
+
+      - name: Print Notice
+        uses: actions/github-script@v6
+        env:
+          NETLIFY_URL: ${{ steps.netlify.outputs.deploy-url }}
+        with:
+          script: |
+            const {NETLIFY_URL} = process.env
+            core.notice(`Published to: ${NETLIFY_URL}`)
